pub mod bounty;
pub mod comment_create;
pub mod comment_vote;
pub mod donate;
pub mod exchange;
pub mod fav;
pub mod hentai_at_home;
pub mod home;
pub mod info;
mod local_fav;
mod local_rate;
mod local_search;
pub mod logs;
pub mod manage_folders;
pub mod mpv;
pub mod news;
pub mod perks;
pub mod popular;
pub mod rate;
pub mod reader;
pub mod search;
pub mod stats;
pub mod tag_vote;
pub mod toplists;
pub mod torrents;
pub mod tos;
pub mod upload;
